[build]
  publish = "."
  functions = "netlify/functions"

# Força o redirecionamento caso a rota direta falhe
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
